apiVersion: apps/v1
kind: Deployment
metadata:
  name: steve-deployment
  namespace: steve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steve-deployment
  template:
    metadata:
      labels:
        app: steve-deployment
    spec:
      containers:
      - name: steve
        image: "### YOUR BUILT IMAGE HERE ###"
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: ""
        - name: DB_PORT
          value: ""
        - name: DB_USERNAME
          value: ""
        - name: DB_PASSWORD
          value: ""
        - name: DB_DATABASE
          value: ""
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: ADMIN_USERNAME
          value: ""
        - name: ADMIN_PASSWORD
          value: ""
        - name: WEBAPI_KEY
          value: "STEVE-API-KEY"
        - name: WEBAPI_VALUE
          value: ""
        ports:
        - containerPort: 8180
          name: http
        - containerPort: 8443
          name: https
        livenessProbe:
          httpGet:
            path: /steve/
            port: 8180
          initialDelaySeconds: 300  # 5 minutes to allow Maven build to complete
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /steve/
            port: 8180
          initialDelaySeconds: 300  # 5 minutes to allow Maven build to complete
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
